language: java

jdk:
  - oraclejdk8

before_deploy:
  - mvn -DskipTests package

deploy:
  - provider: releases
    api_key:
      secure: A1eJjlU42Jnj10rlB7BHh0staMJF0FopazBJZ6pM5JQPmc6ESegU9VWL9n7ZAekeQdcrV3rE/T8YtSaTB9DF5VZ1N7d8JV53hIvI8fzb71bGFIPIm0dh3aEzvpHhgnSaKG2D9Mj4WQErBqlvEcMkyZiyufwDovrD0/9EnULIiLLSDOHtIFrHgG6ZmlJJ0xRRPqcXAWyVTxWiOwSEv4JkobKZ0lolgxWJxDgY80ZWYzJzmOhXcQnWqN/wFhTz1uPsc16daDRqCim6a8uxFTJtDomdEVTiAwjpHbpFo7TU3ltYePopowgCCj1gEUyioQqCFNZZR1OOzlvcMGgJFB6jpIuHjCChTozmrC9fvrXe+NLr0sVmVOb+Zqp1A7hZpQmSC6Jc0LdJ3T5wjBRTYJsR5r9hJYSBvw05X0W6RP9vjn9BWHZNXI+fTXsvp31sdItZhGmTqOByDsYFedX3eNjjklumTSJcX/czsRfh7qMFRVkzjsFBHSD2F0YoCtCLvvUwAht8+qC8l131lA/MBR9lJELPKSp0GzLXgSXoK9QX+xFRLWM3wBWU+bvHrfA36FoeyaSB/CNFXjYZyz66NsZbEM3xsTwRSX905rjh+XlJbe6zrlXIDAxFLLJQCxx2S2xcg4scdXecss09auyKEWGZ0AVVKCDbG7CEJf1roUp07jM=
    file_glob: true
    file: './**/target/*.jar'
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-starter