sudo: required

language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

before_install:
- sudo apt-get install -y markdown

git:
  depth: false

addons:
  sonarcloud:
    organization: "coffeenet"
    token:
      secure: "tk6Cm1enKzy8Ob9RHHfy/7lfBwDB63dTkNJY8GrU5TWrt9hY2y6sCib1Jw+6Yv6zWKr52NyjfHv4tYYteIAR37DBi8uCvwE27Iu+PAGRLG5JBLVOmCsdZ7igw/GcorphvicB4pAOZ8DBPULlFBoELzqzXmdHOErzBE8v0iI8s7Wxj+D/zLljMe4vQmBD5GE0KY+m/x5CPHOlVHQvr6Q9sP8R15S1z+ipQyw4XIDvoZfopS83oicqucaMOcjBeYNHWZRL1T2rbZCXGi7JeQT85NdXwXkvDV4h+KO6MThNnl3l+Zy4mCc/a4KBg/ovaXFebFz5rEFidVFSyO178UoH57vPwR+e81TzC3zqkFy9v2l7I3eqJ7gwRVW2Zq6pbnBspWq3D2riLJzINs4O+aQqbn8PDxilRYVNivA/nhDhzgfY4Ub4BgCNXHGTQN6vy4PmaSLJmOz9FQxcyKQJIv1duin/ISJRUtc7A8eJhv+FKNhi2/nFLOPklqU+fVNBvEkqI5mRyEziNV5ZRkqlgkqXhlnNFI5GZaeXm68o9s1diEhO4/w2k+tcgfCC00TDOzcQdIooi48asH+eHRfmSC6K8/CUmJ3AeB620j0Ek7fRx0vacQg4fyVwUvkY6p6ORflcQr189g7J9LZY8g4rn1S0Vnbmo6CWqH127ROK+Q5h94o="

script: ./mvnw $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

before_deploy:
  - export RELEASE_NOTES=$(awk -v start=1 '/^#{2}[[:space:]].*$/{n++;next};n==start;n==start+1{exit}' CHANGELOG.md | markdown | awk '{printf "%s",$0} END {print ""}')

deploy:
  - provider: releases
    api_key:
      secure: A1eJjlU42Jnj10rlB7BHh0staMJF0FopazBJZ6pM5JQPmc6ESegU9VWL9n7ZAekeQdcrV3rE/T8YtSaTB9DF5VZ1N7d8JV53hIvI8fzb71bGFIPIm0dh3aEzvpHhgnSaKG2D9Mj4WQErBqlvEcMkyZiyufwDovrD0/9EnULIiLLSDOHtIFrHgG6ZmlJJ0xRRPqcXAWyVTxWiOwSEv4JkobKZ0lolgxWJxDgY80ZWYzJzmOhXcQnWqN/wFhTz1uPsc16daDRqCim6a8uxFTJtDomdEVTiAwjpHbpFo7TU3ltYePopowgCCj1gEUyioQqCFNZZR1OOzlvcMGgJFB6jpIuHjCChTozmrC9fvrXe+NLr0sVmVOb+Zqp1A7hZpQmSC6Jc0LdJ3T5wjBRTYJsR5r9hJYSBvw05X0W6RP9vjn9BWHZNXI+fTXsvp31sdItZhGmTqOByDsYFedX3eNjjklumTSJcX/czsRfh7qMFRVkzjsFBHSD2F0YoCtCLvvUwAht8+qC8l131lA/MBR9lJELPKSp0GzLXgSXoK9QX+xFRLWM3wBWU+bvHrfA36FoeyaSB/CNFXjYZyz66NsZbEM3xsTwRSX905rjh+XlJbe6zrlXIDAxFLLJQCxx2S2xcg4scdXecss09auyKEWGZ0AVVKCDbG7CEJf1roUp07jM=
    file_glob: true
    body: "${RELEASE_NOTES}"
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-starter

  - provider: script
    script: openssl aes-256-cbc -K $encrypted_90f1576e4be3_key -iv $encrypted_90f1576e4be3_iv -in coffeenet.pgp.enc -out coffeenet.pgp -d &&
       gpg --fast-import coffeenet.pgp &&
       ./mvnw $MAVEN_CLI_OPTS deploy --settings ${TRAVIS_BUILD_DIR}/.travis.settings.xml -Prelease
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-starter

after_deploy:
  - "echo TRAVIS_BRANCH=\"${TRAVIS_BRANCH}\" TRAVIS_TAG=\"${TRAVIS_TAG}\" TRAVIS_PULL_REQUEST=\"${TRAVIS_PULL_REQUEST}\""
  - "if [ ! -z \"${TRAVIS_TAG}\" ] && [ \"${TRAVIS_BRANCH}\" == \"${TRAVIS_TAG}\" ] && [ \"${TRAVIS_PULL_REQUEST}\" == \"false\" ]; then chmod a+x ./.scripts/automatic-coffeenet-parent-updater.sh; ./.scripts/automatic-coffeenet-parent-updater.sh $OAUTH_TOKEN; fi"

env:
  global:
  - $MAVEN_CLI_OPTS="--batch-mode"
  - secure: hkNM1Riz9bfXcyI4MDUB4gOPlsB0a8DE7geU0Yiw46KZRYo6RPNsas8G83j994s+DwQknkH9HhCMepsLPiqYIzw4OzFmRk7RnveXEZ2r6J6i8qbDg9Cjuhz0xe9iYbaHovu1uQBrK7BKBYu4aYfmRwxwHqS5L/OgaddYfz24FZ7bZ57YCmtQnH1hfyP1glbVSU1Mxw9soVuFotpgrCPx2bXrHB4hWDZj5QvLCae7EF2eLucolCeCedKtz6ZWBG/HfeTErFVE/MyWMYUGw/eJyuSj9tqm25F+Y1hgNPi6BZPLxfKYxJnh4B0ECvT835u9u3vE57tlmOgHgfBfyGtOXKHNZ0dUhBFQfgFfn/U1BtqUHwtSeoDzQCB7EL2NIsAAHIjUOMxFDje60WFYBH5aODxuruEjxoCoKjH6BcSEoFi8MnkqUc0PQcwBf88+tYc5McTLyV7gLjvJaFsqufTo1/c/ZCh5Oa7b7uuKt75TQ064MKI9/Qf2474dBpBE4+7DD7BduS0F2Hwy2jFB1yX+cOgqGaaK5aRUfzVeaIsFAuNbc25LU6MCej8y9bT440VXYjdLXepVehblTIHshFWgu6+Fc5LLn2wjHHYAI/3hVkG/W0svI1EKfRoNBfkaUFwyNUXF6yI+BE7sYD19Of1ZjJwXMkmOpVGNu0AmOkM6n7I=
  - secure: UgSogOby+Y6LaTu+Q76ug/ZdYucLLDcxMUVO8XO5IpPU/a1pKUVvfP6njJQGRdoHvh0JsvaDYPpPgVlh0Jkvj9Sf2f+v8GGP6liVGszFkl4CBYmRRv8O7OKfwd3j3LVMEFFvhmmwnCR/9uwxGQPZlfN5P0Dw0y2BXwPfjP7k0GuIl5JG0qbGSIQ1gISEsPdQ7t/2BACQqTIjSQxybsy2GwoSbrC7G0SyaPnyijH9LeHjHa0hPnkVbPINnv0TFKvNTSFOjUrygHzdp+V1PH9GwKPaAnnieT8Erjp/9XOnvGQFBBRO5YJAbKn6dJSRGC03B28WokbCu6lKPeDnkUL2IQcPjHnKFPGKlm4+WeJWeVQQ8P9x02DfFg+jaiVFnl95Bt5v6VLBMk4hR5VRU2gfEtkFK9GEioiee/pWdPMl06bpLYaUd/U1ky8lYOhmBP10ghmJ8n1Sg5BdNYTszWEMohkqVWdo4kqpCeOaWZYxg1IAIZyoGMwgvA+kmE3JwTVtLMRuZN9AjqR1f0Z6IzhtLTjFaz+Z/Z91GlGPNvahGeYlvKcDICUkO9Z/57/CF1rsa4No5gd3wZX0b+DXpvkD02UaiPWaG1GD/V+V5FPBR+9sQ1nm0a8zSNM2MR/tuc9yT70d97eKSDrxqkoNegUZoYDMQCl3BpBQt3Nqb7he9ro=
  - secure: Q3qMAUC9zUZR8wZCdCsIseCKtyhhGH/WTtFCHvvQ1uZQX6kf/knuV3hEyxUHcb6LzICmSHSPvUkrJy3diYuBxopeF6zO2PtsWIzXS91QfHK30tVevXCwyQOD9GX3cFBLTwklP309g/tcjWzVCFJUk2Y39PlzkvCEGNq0VPtQhlxbxEPO29Bdkh2v5qyvevJIDkSoo3ZMjEnO54vnkI+IhnFvSGeAgFvB9AeR6HhkcgF8YhneAoKCEjBYZxcUChr8wO+1fPYHCAifyFCE8qPZxSj4U8Pm9YYcTm/HPIpgwFAzRCNY3vsHA1jCZAQ0Wqo3aRPCtaThIP87qjOAuM0O4fup3iAfSgROmS23knSoBBH/kn7gpLus6alViK1X4HTzkkmvgkEU5zoWKgXY2FJxjoJ5Vu7BO/kXqqvavgGCtVcY3tw0r0XXPzVJDNt+G795u0105Y9ccqVxBJldbrqh0B0eJ6dhRbI85yQSsXM7Ud7MCZZKiaF9yg1S8j2VWXLmgYejc7LfB56XlSycCEJ2ntxWn3vKrmCga4MENOImNhSM6SMyoFubikLP15yyq+MER3KKXKClDUOmQ1Ltl5cw1AdB/HAAqHCKbdUdQueqTPVzTeOvDpbQH6eOWBptqt9/MRQp+oCLFBKjDItXKgr7NEB5uZqYZ6JpJzU+7cVKmP4=
  - secure: QuXZSfvH2AolibutCJYkSbNNe/jZEtMKF+bX+MUofZ1IxlocLW7YQr1/2VHKQHuQKLrlVv3U9fr8IObN1S+Lx+/pCGxNQSEvmT7Q3XjZ+y70S5xP+4UpVYsSOzIZ0Y7MJGYtwF5xVHFIbxlTAjcXNLmy0z0GSn1G6nbf4xQKCg7H8M669HiGr0/I/oEmF7EKU6cUDMzhuk2SzIfEEEGa2bzB1WuCvn/GpGqgRq+0Ov7CCQ0ysXcPLKOqXhkGNgxYBoxCrXXnZdyihY77yKJO17e6UZWIAXY7+QK+NCqwCokasKCaDDJYz8EesXnvCvencNPpDEl+AdwICdZNNLRUj7rJ1R893ZqD7GpdLTSbQBBHMTnYXXXFIrGKrV2OLexVjYd/V6c+BuSjBNMpOoRjZFMzHWd48VeLtJkw7rGjCeT+rPR2oXBkzarsQyo/Gz+Ys95uQ6IuzycCyZMldh+dg6PA7xt/0BN7ePqwnURIiQnS/JS8x53d8/Wc3RcrbK166ysI1ZI3LYxKw6udqkcrXwNAG8u40SRrCFbFzrJP/uzRL2Xt8Zr1X82SKX25419VbN0wBvMchk8Xcp26N8Xf6HreGtgiNXRSIcwzqTPpRoJPe7Gj5Qa6oHyjumVwQHDB6G3iph313LaL9na9oLJHJrt8Wuguqv+VLKAJPpptxJ8=
