name: CoffeeNet Build & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch target branch for SonarQube branch analysis
      run: |
        git fetch --no-tags --prune origin \
          +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      if: github.event_name == 'pull_request'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify Gradle Wrapper version
      uses: gradle/wrapper-validation-action@v1
    - name: Recreate caches
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build and verify with Gradle
      run: |
        if [ ! -z $SONAR_TOKEN ]; then
          ./gradlew --build-cache clean check sonarqube \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=coffeenet \
            -Dsonar.projectKey=rocks.coffeenet:coffeenet-starter
        else
          ./gradlew --build-cache clean check
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
