name: CoffeeNet Gradle Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify Gradle Wrapper version
      uses: gradle/wrapper-validation-action@v1
    - name: Recreate caches
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build and verify with Gradle
      run: >
        ./gradlew clean check sonarqube
        --build-cache
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=coffeenet
        -Dsonar.projectKey=rocks.coffeenet:coffeenet-starter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
